name: Java CI with Gradle

on:
  push:
    branches:
      - develop
      - main  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build backend and webapp
      run: ./gradlew clean build

    - name: Run unit tests
      run: ./gradlew test  # Run unit tests and generate results in JUnit format

    - name: Upload JUnit Test Results
      uses: dawidd6/action-import-test-results@v2
      with:
        test-results: 'build/test-results/test/*.xml'  # Path to the test results

    - name: Package webapp as JAR
      run: ./gradlew :webapp:bootJar
        
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-artifacts
        path: |
          webapp/build/libs/*.jar
